### ISSUE TITLE
Fix Typos

### ISSUE THREAD

**Issue by SulaimanAminuBarkindo** [ismaelsadeeq/Data-Structures-Algorithms-Problems#17]
I went through the README.md and CONTRIBUTING.md. The documentation is good and straight to the point. However, I spotted some typos that need to be fixed. I would like to fix the typos if nobody is already working on it.

**Comment by ismaelsadeeq** [comment]
Hello @SulaimanAminuBarkindo yes Sure this issue is assigned to you.

**Comment by Debarpan08** [comment]
@ismaelsadeeq Sir, would you please assign this task to me as well?

**Comment by SulaimanAminuBarkindo** [comment]
I opened a PR for this issue kindly review. Thanks

**Comment by ismaelsadeeq** [comment]
Hello @Debarpan08 @SulaimanAminuBarkindo  is already working on this issue.
Thank you
