### ISSUE TITLE
HashMap - Word Frequency - Dart

### ISSUE THREAD

**Issue by fz3hra** [ismaelsadeeq/Data-Structures-Algorithms-Problems#32]
Please assign this to me as I would love to work on it using HashMap

Thanks.

**Comment by fz3hra** [comment]
Please I would like to turn this into Dart rather than Java, thank you.

**Comment by ismaelsadeeq** [comment]
hello @fz3hra Are you still working on this?

**Comment by fz3hra** [comment]
@ismaelsadeeq it was already done

**Comment by ismaelsadeeq** [comment]
Okay, closing this.
