### ISSUE TITLE
Binary Search Implementation with python

### ISSUE THREAD

**Issue by ismaelsadeeq** [ismaelsadeeq/Data-Structures-Algorithms-Problems#4]
Implementing  a binary search algorithm with python.

**Comment by deepesh16b** [comment]
please assign this to me

**Comment by ismaelsadeeq** [comment]
Hi dopesh kindly read the Contributing.md before contributing.
This issue is assigned to you.

**Comment by deepesh16b** [comment]
hello sir,
I am a newbie and I have a question that 
Can I still fork a repo and create a PR even if you have not assigned me that project?

**Comment by ismaelsadeeq** [comment]
No, you should wait to be assigned an issue first before you start working on it.
