### ISSUE TITLE
2D Array - hourglass Java from hackerRank

### ISSUE THREAD

**Issue by fz3hra** [ismaelsadeeq/Data-Structures-Algorithms-Problems#7]
Please take reference to this:
https://www.hackerrank.com/challenges/2d-array/problem

I would like to work on this issue, and would be glad if you could please assign it to me.

Thanks,
Zaahra.

**Comment by ismaelsadeeq** [comment]
Create a new folder 2DArray inside Array folder add ReadMe.md not 2DArray.md as well.
